/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("finalprojectpart2_tkodi1s.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":score"))
    implementation(project(":hand"))
    implementation(project(":die"))
    implementation(project(":ai"))
}

application {
    // Define the main class for the application.
    mainClass.set("finalprojectpart2_tkodi1s.app.App")
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}