/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package finalprojectpart2_tkodi1s.app;

import finalprojectpart2_tkodi1s.app.CLI;

// import finalprojectpart2_tkodi1s.app.GUI;

public class App {

    public static void main(String[] args) {
        CLI cli = new CLI();
        // GUI gui = new GUI();
    }
}
